In [1]:
import torch

from chadhmm import MultinomialHMM
from chadhmm.utilities import constraints

# Initialize Multinomial HMM with 6 states and 4 emissions
hmm = MultinomialHMM(
    n_states=6, n_features=4, n_trials=2, transitions=constraints.Transitions.ERGODIC
)

# Mock the example data and one hot encode
train_seq = torch.randint(0, hmm.n_features, (10000,))
one_hot = hmm.n_trials * torch.nn.functional.one_hot(train_seq, 4)

In [2]:
hmm.fit(X=one_hot, max_iter=5, lengths=[4000, 6000], n_init=1, verbose=False)

MultinomialHMM(
  (_params): ParameterDict(
      (A): Object of type: Categorical
      (emission_pdf): Object of type: Multinomial
      (pi): Object of type: Categorical
  )
)

In [4]:
# Compute log likelihood of generated sequence (set by_sample=False for joint log likelihood)
log_likes = hmm.score(one_hot, lengths=[4000, 6000], by_sample=True)
print(log_likes)

# Compute Akeike Information criteria for each sequence (AIC, BIC or HQC)
ics = hmm.ic(one_hot, lengths=[4000, 6000], criterion=constraints.InformCriteria.AIC)
print(ics)

tensor([-5549.8136, -8314.6634], dtype=torch.float64)
tensor([11205.6272, 16735.3268], dtype=torch.float64)


In [8]:
# Get the most likely sequence using Viterbi algorithm (MAP also available)
viterbi_path = hmm.predict(one_hot, lengths=[4000, 6000], algorithm="viterbi")
print(viterbi_path)

[tensor([4, 4, 4,  ..., 3, 3, 3]), tensor([4, 0, 1,  ..., 5, 0, 3])]


In [9]:
viterbi_path[1]

tensor([4, 0, 1,  ..., 5, 0, 3])